

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sarra
 */
public class EnterName extends javax.swing.JFrame {
    String name;
    InputStream in ;
    AudioInputStream ais ;
    Clip clip;
    
    Font pixelmix;
    /**
     * Creates new form LoginFrame
     */
    public EnterName() throws UnsupportedAudioFileException, LineUnavailableException, IOException, FontFormatException {
        initComponents();
        setTitle("ENTER NAME");
        setSize(395,265);
        setLocationRelativeTo(null);
          try {
             pixelmix = Font.createFont(Font.TRUETYPE_FONT, new File("src\\\\fonts\\\\pixelmix_bold.ttf")).deriveFont(30f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,new File("src\\\\fonts\\\\pixelmix_bold.ttf")));
        } catch(IOException | FontFormatException e){
            
        } 
        labell.setFont(pixelmix);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labell = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        Play = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labell.setFont(pixelmix);
        labell.setForeground(new java.awt.Color(255, 255, 255));
        labell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labell.setText("USERNAME");
        getContentPane().add(labell);
        labell.setBounds(92, 22, 200, 40);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(63, 80, 261, 28);

        Play.setBackground(new java.awt.Color(153, 153, 153));
        Play.setFont(new java.awt.Font("Russo One", 0, 18)); // NOI18N
        Play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        getContentPane().add(Play);
        Play.setBounds(50, 140, 130, 50);

        Exit.setBackground(new java.awt.Color(153, 153, 153));
        Exit.setFont(new java.awt.Font("Russo One", 0, 18)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitt.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(210, 140, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerBG.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed
        //button sound 
        File file = new File("src\\\\wav\\\\button.wav");
        try {
            ais = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(ais);
            clip.start();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:  
        
        name = username.getText();

        if (!username.getText().isEmpty()){  
             int x = 0;
             int size=0;
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample","app","app");
                Statement stmt = con.createStatement(); 
                ResultSet rs = stmt.executeQuery("SELECT * FROM APP.scoreboard");
                while (rs.next()){
                    size ++;
                    if (name.equals(rs.getString("username"))){
                        JOptionPane.showMessageDialog(null,"Name already used", "problem", JOptionPane.WARNING_MESSAGE);
                    } 
                  // if (!name.equals(rs.getString("username"))){
                    else { 
                       x ++;
                    } 
                } 
                if (x == size ){
                    mainFrame frame = null;
                     try {
                         frame = new mainFrame();
                     } catch (IOException | UnsupportedAudioFileException | LineUnavailableException | FontFormatException ex) {
                         Logger.getLogger(EnterName.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 frame.setSize(700, 700); 
                 frame.setLocationRelativeTo(null); /* to start in the middle instead of the left corner */
                 frame.setResizable(false);
                 frame.setTitle("Platform Game");
                 frame.setVisible(true); 
                 frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
                 
                 Calendar timestamp = Calendar.getInstance();
                 java.util.Date currenttime = timestamp.getTime();
                 
                 System.out.print("Hello "+ name+"! Have fun ");
                        stmt.executeUpdate("DELETE FROM APP.CURRENT_PLAYER ");
                        stmt.executeUpdate("INSERT INTO APP.CURRENT_PLAYER "        
                        +" VALUES ('"+username.getText()+"')"); 
                        stmt.executeUpdate("INSERT INTO APP.SCOREBOARD "        
                        +" VALUES ('"+username.getText()+"',0)");
                      
                    dispose(); 
                   
                     
                }
            
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(EnterName.class.getName()).log(Level.SEVERE, null, ex);
            } 
/*
            mainFrame frame = new mainFrame();
            frame.setSize(700, 700);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.setVisible(true);
            frame.setTitle("Platform Game");
            frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
             */ 
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Please enter a name", "problem", JOptionPane.WARNING_MESSAGE);
        }
          
    }//GEN-LAST:event_PlayActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameActionPerformed
    
    
    
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //button sound 
        File file = new File("src\\\\wav\\\\button.wav");
        try {
            ais = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(ais);
            clip.start();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
         dispose();
       
         
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EnterName().setVisible(true);
                } catch (UnsupportedAudioFileException | LineUnavailableException | IOException | FontFormatException ex) {
                    Logger.getLogger(EnterName.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public String getUsername() {
        return name;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Play;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labell;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
