/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */

public class Scoreboard extends javax.swing.JFrame {
    
    AudioInputStream ais ;
    Clip clip ;
    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() throws IOException {
        initComponents();
        show_user();
        setTitle("GIOMES Platform Game scoreboard");
        setSize(710,660);
        setLocationRelativeTo(null);
    }
    
 public ArrayList<Character> userList(){
      ArrayList<Character> Players = new ArrayList<>();   
     try {
          
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample","app","app");
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery("SELECT * FROM APP.SCOREBOARD ORDER BY SCORE DESC");
            Character character;
            while (rs.next()){
                character = new Character(rs.getInt("score"),rs.getString("username"));
                Players.add(character);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Scoreboard.class.getName()).log(Level.SEVERE, null, ex);
        }
       return Players;  
    }
    
    public void show_user() {
        ArrayList<Character> list = userList();
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        Object[] row = new Object[2];
        for (int i=0;i<list.size();i++) {
            row[0] = list.get(i).getUsername();
            row[1] = list.get(i).getScore();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        table.setBackground(new java.awt.Color(140, 167, 244));
        table.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setToolTipText("");
        table.setEnabled(false);
        table.setGridColor(new java.awt.Color(140, 167, 244));
        table.setSelectionForeground(new java.awt.Color(140, 167, 244));
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(120, 150, 440, 370);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(510, 550, 173, 38);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sarra\\Desktop\\game\\Biomes\\Assets\\mainMenu.png")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(433, 69));
        jButton1.setMinimumSize(new java.awt.Dimension(433, 69));
        jButton1.setPreferredSize(new java.awt.Dimension(433, 69));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 550, 173, 38);
        jButton1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sarra\\Desktop\\game\\Biomes\\Assets\\scoreBG.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //button sound 
        File file = new File("src\\\\wav\\\\button.wav");
        try {
            ais = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(ais);
            clip.start();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        System.out.println("\n Thank you for playing!");
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //button sound 
        File file = new File("src\\\\wav\\\\button.wav");
        try {
            ais = AudioSystem.getAudioInputStream(file);
            clip = AudioSystem.getClip();
            clip.open(ais);
            clip.start();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
        dispose(); 
        MainMenu mframe = new MainMenu();
        
        mframe.setSize(700, 700); 
        
        mframe.setLocationRelativeTo(null); /* to start in the middle instead of the left corner */
        
        mframe.setResizable(false);
        mframe.setTitle("Platform Game");
        mframe.setVisible(true); 
        
        mframe.setDefaultCloseOperation(EXIT_ON_CLOSE); 
    }//GEN-LAST:event_jButton1ActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scoreboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try { 
                    new Scoreboard().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Scoreboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}

